development:
  auth0_domain: "https://localhost:3000"
test:
  auth0_domain: "https://localhost:3000"
production:
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
