development:
  auth0_domain: "https://localhost:3000"
  auth0_client_id: "AUTH0_DEV_CLIENT_ID"
  auth0_client_secret: "AUTH0_DEV_CLIENT_SECRET"
test:
  auth0_domain: "https://localhost:3000"
  auth0_client_id: "AUTH0_TEST_CLIENT_ID"
  auth0_client_secret: "AUTH0_TEST_CLIENT_SECRET"
production:
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
